services:
  ncat:
    image: stephengpope/no-code-architects-toolkit:latest
    env_file:
      - .env
    ports:
      - "5050:8080"
    volumes:
      - storage:/var/www/html/storage/app
      - logs:/var/www/html/storage/logs
      - ./routes:/app/routes
    restart: unless-stopped
    environment:
      - LOCAL_STORAGE_PATH=/tmp
      - STORAGE_BACKEND=local

    networks:
      - n8n_network

volumes:
  storage:
    driver: local
  logs:
    driver: local

networks: 
  n8n_network:
    external: true
